# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoDeleteUser.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditEmailAddress = QtWidgets.QLineEdit(Dialog)
        self.lineEditEmailAddress.setObjectName("lineEditEmailAddress")
        self.verticalLayout.addWidget(self.lineEditEmailAddress)
        self.lineEditPassword = QtWidgets.QLineEdit(Dialog)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout.addWidget(self.lineEditPassword)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.pushButtonDelete = QtWidgets.QPushButton(Dialog)
        self.pushButtonDelete.setStyleSheet("background-color: rgb(254, 167, 152);")
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.verticalLayout_3.addWidget(self.pushButtonDelete)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelSure = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.labelSure.setFont(font)
        self.labelSure.setObjectName("labelSure")
        self.horizontalLayout_3.addWidget(self.labelSure)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonYes = QtWidgets.QPushButton(Dialog)
        self.pushButtonYes.setObjectName("pushButtonYes")
        self.horizontalLayout_2.addWidget(self.pushButtonYes)
        self.pushButtonNo = QtWidgets.QPushButton(Dialog)
        self.pushButtonNo.setObjectName("pushButtonNo")
        self.horizontalLayout_2.addWidget(self.pushButtonNo)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.labelResponse = QtWidgets.QLabel(Dialog)
        self.labelResponse.setMaximumSize(QtCore.QSize(16777215, 150))
        self.labelResponse.setStyleSheet("background-color: rgb(254, 188, 142);\n"
"background-color: rgb(222, 255, 175);")
        self.labelResponse.setText("")
        self.labelResponse.setObjectName("labelResponse")
        self.verticalLayout_3.addWidget(self.labelResponse)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Borrando información de una base de datos"))
        self.label.setText(_translate("Dialog", "Correo electrónico"))
        self.label_2.setText(_translate("Dialog", "Contraseña"))
        self.pushButtonDelete.setText(_translate("Dialog", "Borrar usuario"))
        self.labelSure.setText(_translate("Dialog", "¿Estás seguro?"))
        self.pushButtonYes.setText(_translate("Dialog", "Sí"))
        self.pushButtonNo.setText(_translate("Dialog", "No"))

